### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by JeffersonSchuler** [rubanraj54/vue-bootstrap4-table#12]
Thanks for working on this control, it is very useful.

Everything seems to be functioning fine, but I am running into some UI issues that might be caused by my lack of experience with Vue and CSS.  

Currently the sort arrows are not being rendered.  Just 2 boxes are being displayed in their place.  I am seeing the same behavior when viewing your demo page.  https://rubanraj54.gitbook.io/vue-bootstrap4-table/demo

My other UI issue is regarding the global search box.  The width of the text box is truncating the placeholder text, and the clear text button is extending below the text control.  The clear text button behavior started to happen when I switch to using web pack's require function when referencing the Bootstrap CSS file.  Before I was including the CSS via a link tag in the main index.html file.  

Any suggestions or comments would be appreciated.

Thanks.

-Jeff-

**Comment by Chris-Pratt-Clystnet** [comment]
Your first issue seems like strange one as it renders for me both on my own implementation and on the demo site, I would check that you don't have some weird caching issue.

The second issue I have run into my self and I think that area needs more work as it doesn't look great down at mobile level and at tablet level it can get a little weird. What I would like to see is this turned into a slot so that we can alter the layout to what we want.

**Comment by rubanraj54** [comment]
Hi @JeffersonSchuler, 

VueBootstrap4Table uses unicodes to show sort arrows and not all browsers and font types support all types of Unicode.  Even I faced this issue, the sort arrows are visible in my laptop and not in my mobile phone. Ref: https://stackoverflow.com/questions/15183061/does-every-browser-support-all-unicode

And I don't want to use an image for sort arrows by default, since eventually it will increase the size of this package.

**Solution:**
VueBootstrap4Table let you customize the sort icons as per your preference. You can find how to override the sort icons in this link https://rubanraj54.gitbook.io/vue-bootstrap4-table/sorting#slot

Issue two:
I am currently working on the proper alignment of the clear button in all input boxes.
Hopefully, you'll see the clear buttons inside the input text boxes in the future version (approx. release in next week).

Cheers,
Ruby.

@Chris-Pratt-Clystnet Thanks for helping out.

**Comment by rubanraj54** [comment]
Hi @JeffersonSchuler @Chris-Pratt-Clystnet 

Reg second issue (clear button breaks down to the second line in smaller devices), I have made a clear button inside the input text itself with hover effects which looks nice in all screen size, and you won't get the issue again.

I made a few improvements too, the user can now decide whether he needs a clear button or not.
And the user can use a slot to change the clean button icon.

Sample:
![screenshot from 2019-03-01 09-34-48](https://user-images.githubusercontent.com/10024405/53626463-0ef63e80-3c06-11e9-86a0-de08b0806481.png)

Your feedbacks are welcome.

Cheers,
Ruby.

**Comment by Chris-Pratt-Clystnet** [comment]
Those changes look great and just what I was looking for :-)

**Comment by JeffersonSchuler** [comment]
> Hi @JeffersonSchuler @Chris-Pratt-Clystnet
> 
> Reg second issue (clear button breaks down to the second line in smaller devices), I have made a clear button inside the input text itself with hover effects which looks nice in all screen size, and you won't get the issue again.
> 
> I made a few improvements too, the user can now decide whether he needs a clear button or not.
> And the user can use a slot to change the clean button icon.
> 
> **Sample 1 (default):**
> ![screenshot from 2019-03-01 09-34-48](https://user-images.githubusercontent.com/10024405/53626463-0ef63e80-3c06-11e9-86a0-de08b0806481.png)
> 
> **Sample 2 (custom fa icon via slot):**
> ![screenshot from 2019-03-01 09-48-40](https://user-images.githubusercontent.com/10024405/53626972-7496fa80-3c07-11e9-8d5c-43ae3e538b82.png)
> 
> Your feedbacks are welcome.
> 
> Cheers,
> Ruby.

Those changes are most welcome.  Thank you.

**Comment by rubanraj54** [comment]
Hi @JeffersonSchuler @Chris-Pratt-Clystnet 

A new release has been rolled out today. You can update your package to get this new feature.

I will close this issue now.

Cheers,
Ruby.
