### ISSUE TITLE
Action button out of view with wide column

### ISSUE THREAD

**Issue by pordonez** [rubanraj54/vue-bootstrap4-table#27]
Hi,

Not sure if anything can be done about this but I noticed that the action button(s) can become out of view with wide columns.  I reproduced the issue with your code pen.  Notice that the Download button is out of view.
<img width="1126" alt="Screen Shot 2019-03-18 at 10 19 45 PM" src="https://user-images.githubusercontent.com/235676/54575976-ba580f00-49cc-11e9-8039-3044b0d37a29.png">
Please let me know your thoughts on this behavior.

Kindly,
Peter

**Comment by rubanraj54** [comment]
Hi @pordonez,

I also faced this issue a few months back.

I had only two options,

**Option 1**
Let the user scroll left to find the action buttons, I know this is an ugly option.

![Screenshot from 2019-03-19 21-22-57](https://user-images.githubusercontent.com/10024405/54639854-a83ea500-4a8e-11e9-916c-964f55647506.png)


**Option 2**
 Apply your custom class to all <td> with style "word-break: break-all;" which breaks the long word into multiple lines, and now the action buttons will always be visible to the user.


![Screenshot from 2019-03-19 21-29-51](https://user-images.githubusercontent.com/10024405/54639985-f784d580-4a8e-11e9-97b3-42cf25b7c72f.png)


**New idea (Just now I thought of this)**

I can provide an empty row at the top as a slot so that users can render whatever they want and place buttons wherever they like. What do you think about this feature?

Cheers,
Ruby.

**Comment by pordonez** [comment]
Super!  I'll try option 2 for now, and consider modifying the empty row when/if that feature becomes available.  Thank you, Peter

**Comment by rubanraj54** [comment]
You're welcome @pordonez .

I updated my comment above FYI.

And I hope, you know to add your custom class to cells.

Cheers,
Ruby.
